import { randomUUID } from 'node:crypto'
import { readFileSync } from 'node:fs'
import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'

const apiTarget = process.env.LOREX_API_URL ?? 'http://localhost:5180'

// The one application version: package.json's. Shown as "LoreX v…" and nowhere else written down.
const { version } = JSON.parse(
  readFileSync(new URL('./package.json', import.meta.url), 'utf8'),
) as {
  version: string
}

// Which build this is, fixed once per Vite start: a deployment's own id if it gives one, else the commit GitHub Actions
// is building, else a fresh random one. The service worker names its cache after it, so every build starts clean.
// Only these characters reach the page, whatever the environment held.
const buildId = (
  process.env.LOREX_BUILD_ID ||
  process.env.GITHUB_SHA?.slice(0, 12) ||
  randomUUID().slice(0, 8)
)
  .replace(/[^A-Za-z0-9._-]/g, '')
  .slice(0, 40)

// https://vite.dev/config/
export default defineConfig({
  plugins: [react()],
  define: {
    __LOREX_VERSION__: JSON.stringify(version),
    __LOREX_BUILD_ID__: JSON.stringify(buildId),
  },
  server: {
    port: 5173,
    strictPort: true,
    proxy: {
      // Keeps the browser on a single origin in development, so no CORS round trips.
      '/api': { target: apiTarget, changeOrigin: true },
      '/health': { target: apiTarget, changeOrigin: true },
      // Generated by the API from the public predicates (ADR 0038), so the dev server asks it.
      '/robots.txt': { target: apiTarget, changeOrigin: true },
      '/sitemap.xml': { target: apiTarget, changeOrigin: true },
    },
  },
  preview: {
    port: 4173,
    strictPort: true,
  },
  build: {
    outDir: 'dist',
    sourcemap: true,
  },
})
