// <auto-generated />
using System;
using Lorex.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lorex.Api.Data.Migrations
{
    [DbContext(typeof(LorexDbContext))]
    [Migration("20260914163547_AddUniverseSearchIndex")]
    partial class AddUniverseSearchIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Lorex.Api.Features.Auth.LorexUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.CanonIntegrity.CanonConflict", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UniverseId", "Fingerprint")
                        .IsUnique();

                    b.HasIndex("UniverseId", "Status", "Severity");

                    b.ToTable("CanonConflicts", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.CanonIntegrity.CanonConflictSubject", b =>
                {
                    b.Property<Guid>("ConflictId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SubjectKind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("ConflictId", "SubjectKind", "SubjectId", "Role");

                    b.HasIndex("SubjectKind", "SubjectId");

                    b.ToTable("CanonConflictSubjects", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Chronology.ChronologyEra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LabelPosition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UniverseId", "SortOrder")
                        .IsUnique();

                    b.ToTable("ChronologyEras", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Ideas.Idea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UniverseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "DeletedAt", "UpdatedAt");

                    b.HasIndex("UniverseId", "DeletedAt", "UpdatedAt");

                    b.ToTable("Ideas", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Ideas.IdeaEntityReference", b =>
                {
                    b.Property<Guid>("IdeaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.HasKey("IdeaId", "EntityId");

                    b.HasIndex("EntityId");

                    b.ToTable("IdeaEntityReferences", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Ideas.IdeaPlotArcReference", b =>
                {
                    b.Property<Guid>("IdeaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlotArcId")
                        .HasColumnType("TEXT");

                    b.HasKey("IdeaId", "PlotArcId");

                    b.HasIndex("PlotArcId");

                    b.ToTable("IdeaPlotArcReferences", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Ideas.IdeaPlotBeatReference", b =>
                {
                    b.Property<Guid>("IdeaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlotBeatId")
                        .HasColumnType("TEXT");

                    b.HasKey("IdeaId", "PlotBeatId");

                    b.HasIndex("PlotBeatId");

                    b.ToTable("IdeaPlotBeatReferences", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Ideas.IdeaSceneReference", b =>
                {
                    b.Property<Guid>("IdeaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("TEXT");

                    b.HasKey("IdeaId", "SceneId");

                    b.HasIndex("SceneId");

                    b.ToTable("IdeaSceneReferences", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Ideas.IdeaStoryReference", b =>
                {
                    b.Property<Guid>("IdeaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StoryId")
                        .HasColumnType("TEXT");

                    b.HasKey("IdeaId", "StoryId");

                    b.HasIndex("StoryId");

                    b.ToTable("IdeaStoryReferences", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "Value")
                        .IsUnique();

                    b.ToTable("EntityAliases", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityArticle", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("EntityId");

                    b.ToTable("EntityArticles", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityArticleRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RestoredFromRevisionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "Number")
                        .IsUnique();

                    b.ToTable("EntityArticleRevisions", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityFieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EntityTypeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Semantic")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntityTypeId", "Name")
                        .IsUnique();

                    b.HasIndex("EntityTypeId", "Semantic")
                        .IsUnique()
                        .HasFilter("\"Semantic\" IS NOT NULL");

                    b.ToTable("EntityFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityFieldOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FieldDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FieldDefinitionId", "Value")
                        .IsUnique();

                    b.ToTable("EntityFieldOptions", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EraId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FieldDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("NumberValue")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("OptionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReferencedEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextValue")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EraId");

                    b.HasIndex("FieldDefinitionId");

                    b.HasIndex("OptionId");

                    b.HasIndex("ReferencedEntityId");

                    b.HasIndex("EntityId", "FieldDefinitionId");

                    b.ToTable("EntityFieldValues", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityImage", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("CropHeight")
                        .HasColumnType("REAL");

                    b.Property<double?>("CropWidth")
                        .HasColumnType("REAL");

                    b.Property<double?>("CropX")
                        .HasColumnType("REAL");

                    b.Property<double?>("CropY")
                        .HasColumnType("REAL");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ThumbnailId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntityId");

                    b.ToTable("EntityImages", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CanonStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Changes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasMaxLength(200000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityTypeName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RestoredFromRevisionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "Number")
                        .IsUnique();

                    b.ToTable("EntityRevisions", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityRevisionAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RevisionId");

                    b.ToTable("EntityRevisionAliases", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityRevisionFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("EraId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EraLabel")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FieldDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("NumberValue")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("OptionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionValue")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReferencedEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferencedEntityName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextValue")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RevisionId");

                    b.ToTable("EntityRevisionFieldValues", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityRevisionTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RevisionId");

                    b.ToTable("EntityRevisionTags", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntitySearchFieldMatch", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Field")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Rank")
                        .HasColumnType("REAL");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntitySearchMatch", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Rank")
                        .HasColumnType("REAL");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityTag", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("EntityId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("EntityTags", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccentColor")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UniverseId", "DisplayOrder");

                    b.HasIndex("UniverseId", "Name")
                        .IsUnique();

                    b.ToTable("EntityTypes", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.LoreEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CanonStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityTypeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityTypeId");

                    b.HasIndex("UniverseId", "EntityTypeId");

                    b.HasIndex("UniverseId", "Name");

                    b.HasIndex("UniverseId", "DeletedAt", "IsArchived", "UpdatedAt");

                    b.ToTable("Entities", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UniverseId", "Slug")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Profile.ProfileImage", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("CropHeight")
                        .HasColumnType("REAL");

                    b.Property<double?>("CropWidth")
                        .HasColumnType("REAL");

                    b.Property<double?>("CropX")
                        .HasColumnType("REAL");

                    b.Property<double?>("CropY")
                        .HasColumnType("REAL");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ThumbnailId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("ProfileImages", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Relationships.LoreRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CanonStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RelationshipTypeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceEntityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetEntityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RelationshipTypeId");

                    b.HasIndex("SourceEntityId");

                    b.HasIndex("TargetEntityId");

                    b.HasIndex("UniverseId", "SourceEntityId");

                    b.HasIndex("UniverseId", "TargetEntityId");

                    b.ToTable("Relationships", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Relationships.RelationshipType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AgeOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InverseName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSymmetric")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxAgeDifferenceYears")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinAgeDifferenceYears")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UniverseId", "DisplayOrder");

                    b.HasIndex("UniverseId", "Name")
                        .IsUnique();

                    b.ToTable("RelationshipTypes", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Search.UniverseSearchMatch", b =>
                {
                    b.Property<int>("Field")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Rank")
                        .HasColumnType("REAL");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Stories.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.HasIndex("StoryId", "SortOrder")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("Chapters", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Stories.PlotArc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.HasIndex("StoryId", "SortOrder")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("PlotArcs", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Stories.PlotBeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlotArcId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlotArcId");

                    b.HasIndex("PlotArcId", "SortOrder")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("PlotBeats", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Stories.PlotBeatEntity", b =>
                {
                    b.Property<Guid>("PlotBeatId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.HasKey("PlotBeatId", "EntityId");

                    b.HasIndex("EntityId");

                    b.ToTable("PlotBeatEntities", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Stories.PlotBeatScene", b =>
                {
                    b.Property<Guid>("PlotBeatId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("TEXT");

                    b.HasKey("PlotBeatId", "SceneId");

                    b.HasIndex("SceneId");

                    b.ToTable("PlotBeatScenes", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Stories.Scene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChapterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EraId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PovEntityId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("EraId");

                    b.HasIndex("PovEntityId");

                    b.HasIndex("StoryId");

                    b.HasIndex("ChapterId", "SortOrder")
                        .IsUnique()
                        .HasFilter("\"ChapterId\" IS NOT NULL AND \"DeletedAt\" IS NULL");

                    b.HasIndex("StoryId", "SortOrder")
                        .IsUnique()
                        .HasFilter("\"ChapterId\" IS NULL AND \"DeletedAt\" IS NULL");

                    b.ToTable("Scenes", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Stories.SceneEntityLink", b =>
                {
                    b.Property<Guid>("SceneId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.HasKey("SceneId", "EntityId");

                    b.HasIndex("EntityId");

                    b.ToTable("SceneEntityLinks", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Stories.SceneManuscript", b =>
                {
                    b.Property<Guid>("SceneId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("SceneId");

                    b.ToTable("SceneManuscripts", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Stories.SceneManuscriptRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RestoredFromRevisionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SceneId", "Number")
                        .IsUnique();

                    b.ToTable("SceneManuscriptRevisions", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Stories.Story", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Premise")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UniverseId", "Title");

                    b.ToTable("Stories", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Timeline.TimelineEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CanonStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DateKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EndDay")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("EndEraId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EndMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EraLabel")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartDay")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("StartEraId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EndEraId");

                    b.HasIndex("StartEraId");

                    b.HasIndex("UniverseId", "CanonStatus");

                    b.HasIndex("UniverseId", "DateKind", "StartYear", "StartMonth", "StartDay");

                    b.ToTable("TimelineEntries", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Timeline.TimelineEntryLink", b =>
                {
                    b.Property<Guid>("TimelineEntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.HasKey("TimelineEntryId", "EntityId");

                    b.HasIndex("EntityId");

                    b.ToTable("TimelineEntryLinks", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.Universes.Universe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccentColor")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique();

                    b.HasIndex("OwnerId", "IsArchived", "UpdatedAt");

                    b.ToTable("Universes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Lorex.Api.Features.CanonIntegrity.CanonConflict", b =>
                {
                    b.HasOne("Lorex.Api.Features.Universes.Universe", "Universe")
                        .WithMany()
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("Lorex.Api.Features.CanonIntegrity.CanonConflictSubject", b =>
                {
                    b.HasOne("Lorex.Api.Features.CanonIntegrity.CanonConflict", "Conflict")
                        .WithMany("Subjects")
                        .HasForeignKey("ConflictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conflict");
                });

            modelBuilder.Entity("Lorex.Api.Features.Chronology.ChronologyEra", b =>
                {
                    b.HasOne("Lorex.Api.Features.Universes.Universe", "Universe")
                        .WithMany()
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("Lorex.Api.Features.Ideas.Idea", b =>
                {
                    b.HasOne("Lorex.Api.Features.Auth.LorexUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lorex.Api.Features.Universes.Universe", "Universe")
                        .WithMany()
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("Lorex.Api.Features.Ideas.IdeaEntityReference", b =>
                {
                    b.HasOne("Lorex.Api.Features.Lore.LoreEntity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lorex.Api.Features.Ideas.Idea", "Idea")
                        .WithMany("EntityReferences")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("Lorex.Api.Features.Ideas.IdeaPlotArcReference", b =>
                {
                    b.HasOne("Lorex.Api.Features.Ideas.Idea", "Idea")
                        .WithMany("PlotArcReferences")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lorex.Api.Features.Stories.PlotArc", "PlotArc")
                        .WithMany()
                        .HasForeignKey("PlotArcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("PlotArc");
                });

            modelBuilder.Entity("Lorex.Api.Features.Ideas.IdeaPlotBeatReference", b =>
                {
                    b.HasOne("Lorex.Api.Features.Ideas.Idea", "Idea")
                        .WithMany("PlotBeatReferences")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lorex.Api.Features.Stories.PlotBeat", "PlotBeat")
                        .WithMany()
                        .HasForeignKey("PlotBeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("PlotBeat");
                });

            modelBuilder.Entity("Lorex.Api.Features.Ideas.IdeaSceneReference", b =>
                {
                    b.HasOne("Lorex.Api.Features.Ideas.Idea", "Idea")
                        .WithMany("SceneReferences")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lorex.Api.Features.Stories.Scene", "Scene")
                        .WithMany()
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Lorex.Api.Features.Ideas.IdeaStoryReference", b =>
                {
                    b.HasOne("Lorex.Api.Features.Ideas.Idea", "Idea")
                        .WithMany("StoryReferences")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lorex.Api.Features.Stories.Story", "Story")
                        .WithMany()
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityAlias", b =>
                {
                    b.HasOne("Lorex.Api.Features.Lore.LoreEntity", "Entity")
                        .WithMany("Aliases")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityArticle", b =>
                {
                    b.HasOne("Lorex.Api.Features.Lore.LoreEntity", "Entity")
                        .WithOne()
                        .HasForeignKey("Lorex.Api.Features.Lore.EntityArticle", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityArticleRevision", b =>
                {
                    b.HasOne("Lorex.Api.Features.Lore.LoreEntity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityFieldDefinition", b =>
                {
                    b.HasOne("Lorex.Api.Features.Lore.EntityType", "EntityType")
                        .WithMany("Fields")
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityType");
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityFieldOption", b =>
                {
                    b.HasOne("Lorex.Api.Features.Lore.EntityFieldDefinition", "FieldDefinition")
                        .WithMany("Options")
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityFieldValue", b =>
                {
                    b.HasOne("Lorex.Api.Features.Lore.LoreEntity", "Entity")
                        .WithMany("FieldValues")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lorex.Api.Features.Chronology.ChronologyEra", "Era")
                        .WithMany()
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Lorex.Api.Features.Lore.EntityFieldDefinition", "FieldDefinition")
                        .WithMany("Values")
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lorex.Api.Features.Lore.EntityFieldOption", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Lorex.Api.Features.Lore.LoreEntity", "ReferencedEntity")
                        .WithMany()
                        .HasForeignKey("ReferencedEntityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Entity");

                    b.Navigation("Era");

                    b.Navigation("FieldDefinition");

                    b.Navigation("Option");

                    b.Navigation("ReferencedEntity");
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityImage", b =>
                {
                    b.HasOne("Lorex.Api.Features.Lore.LoreEntity", "Entity")
                        .WithOne("Image")
                        .HasForeignKey("Lorex.Api.Features.Lore.EntityImage", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityRevision", b =>
                {
                    b.HasOne("Lorex.Api.Features.Lore.LoreEntity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityRevisionAlias", b =>
                {
                    b.HasOne("Lorex.Api.Features.Lore.EntityRevision", "Revision")
                        .WithMany("Aliases")
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityRevisionFieldValue", b =>
                {
                    b.HasOne("Lorex.Api.Features.Lore.EntityRevision", "Revision")
                        .WithMany("FieldValues")
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityRevisionTag", b =>
                {
                    b.HasOne("Lorex.Api.Features.Lore.EntityRevision", "Revision")
                        .WithMany("Tags")
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityTag", b =>
                {
                    b.HasOne("Lorex.Api.Features.Lore.LoreEntity", "Entity")
                        .WithMany("EntityTags")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lorex.Api.Features.Lore.Tag", "Tag")
                        .WithMany("EntityTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityType", b =>
                {
                    b.HasOne("Lorex.Api.Features.Universes.Universe", "Universe")
                        .WithMany()
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.LoreEntity", b =>
                {
                    b.HasOne("Lorex.Api.Features.Lore.EntityType", "EntityType")
                        .WithMany()
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lorex.Api.Features.Universes.Universe", "Universe")
                        .WithMany()
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityType");

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.Tag", b =>
                {
                    b.HasOne("Lorex.Api.Features.Universes.Universe", "Universe")
                        .WithMany()
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("Lorex.Api.Features.Profile.ProfileImage", b =>
                {
                    b.HasOne("Lorex.Api.Features.Auth.LorexUser", "User")
                        .WithOne()
                        .HasForeignKey("Lorex.Api.Features.Profile.ProfileImage", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lorex.Api.Features.Relationships.LoreRelationship", b =>
                {
                    b.HasOne("Lorex.Api.Features.Relationships.RelationshipType", "RelationshipType")
                        .WithMany()
                        .HasForeignKey("RelationshipTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lorex.Api.Features.Lore.LoreEntity", "SourceEntity")
                        .WithMany()
                        .HasForeignKey("SourceEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lorex.Api.Features.Lore.LoreEntity", "TargetEntity")
                        .WithMany()
                        .HasForeignKey("TargetEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lorex.Api.Features.Universes.Universe", "Universe")
                        .WithMany()
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelationshipType");

                    b.Navigation("SourceEntity");

                    b.Navigation("TargetEntity");

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("Lorex.Api.Features.Relationships.RelationshipType", b =>
                {
                    b.HasOne("Lorex.Api.Features.Universes.Universe", "Universe")
                        .WithMany()
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("Lorex.Api.Features.Stories.Chapter", b =>
                {
                    b.HasOne("Lorex.Api.Features.Stories.Story", "Story")
                        .WithMany("Chapters")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Lorex.Api.Features.Stories.PlotArc", b =>
                {
                    b.HasOne("Lorex.Api.Features.Stories.Story", "Story")
                        .WithMany("PlotArcs")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Lorex.Api.Features.Stories.PlotBeat", b =>
                {
                    b.HasOne("Lorex.Api.Features.Stories.PlotArc", "PlotArc")
                        .WithMany("Beats")
                        .HasForeignKey("PlotArcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlotArc");
                });

            modelBuilder.Entity("Lorex.Api.Features.Stories.PlotBeatEntity", b =>
                {
                    b.HasOne("Lorex.Api.Features.Lore.LoreEntity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lorex.Api.Features.Stories.PlotBeat", "PlotBeat")
                        .WithMany("EntityLinks")
                        .HasForeignKey("PlotBeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("PlotBeat");
                });

            modelBuilder.Entity("Lorex.Api.Features.Stories.PlotBeatScene", b =>
                {
                    b.HasOne("Lorex.Api.Features.Stories.PlotBeat", "PlotBeat")
                        .WithMany("SceneLinks")
                        .HasForeignKey("PlotBeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lorex.Api.Features.Stories.Scene", "Scene")
                        .WithMany()
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlotBeat");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Lorex.Api.Features.Stories.Scene", b =>
                {
                    b.HasOne("Lorex.Api.Features.Stories.Chapter", "Chapter")
                        .WithMany("Scenes")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Lorex.Api.Features.Chronology.ChronologyEra", "Era")
                        .WithMany()
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Lorex.Api.Features.Lore.LoreEntity", "PovEntity")
                        .WithMany()
                        .HasForeignKey("PovEntityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lorex.Api.Features.Stories.Story", "Story")
                        .WithMany("Scenes")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("Era");

                    b.Navigation("PovEntity");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Lorex.Api.Features.Stories.SceneEntityLink", b =>
                {
                    b.HasOne("Lorex.Api.Features.Lore.LoreEntity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lorex.Api.Features.Stories.Scene", "Scene")
                        .WithMany("EntityLinks")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Lorex.Api.Features.Stories.SceneManuscript", b =>
                {
                    b.HasOne("Lorex.Api.Features.Stories.Scene", "Scene")
                        .WithOne()
                        .HasForeignKey("Lorex.Api.Features.Stories.SceneManuscript", "SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Lorex.Api.Features.Stories.SceneManuscriptRevision", b =>
                {
                    b.HasOne("Lorex.Api.Features.Stories.Scene", "Scene")
                        .WithMany()
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Lorex.Api.Features.Stories.Story", b =>
                {
                    b.HasOne("Lorex.Api.Features.Universes.Universe", "Universe")
                        .WithMany()
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("Lorex.Api.Features.Timeline.TimelineEntry", b =>
                {
                    b.HasOne("Lorex.Api.Features.Chronology.ChronologyEra", "EndEra")
                        .WithMany()
                        .HasForeignKey("EndEraId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Lorex.Api.Features.Chronology.ChronologyEra", "StartEra")
                        .WithMany()
                        .HasForeignKey("StartEraId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Lorex.Api.Features.Universes.Universe", "Universe")
                        .WithMany()
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EndEra");

                    b.Navigation("StartEra");

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("Lorex.Api.Features.Timeline.TimelineEntryLink", b =>
                {
                    b.HasOne("Lorex.Api.Features.Lore.LoreEntity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lorex.Api.Features.Timeline.TimelineEntry", "TimelineEntry")
                        .WithMany("EntityLinks")
                        .HasForeignKey("TimelineEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("TimelineEntry");
                });

            modelBuilder.Entity("Lorex.Api.Features.Universes.Universe", b =>
                {
                    b.HasOne("Lorex.Api.Features.Auth.LorexUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Lorex.Api.Features.Auth.LorexUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Lorex.Api.Features.Auth.LorexUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lorex.Api.Features.Auth.LorexUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Lorex.Api.Features.Auth.LorexUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lorex.Api.Features.CanonIntegrity.CanonConflict", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Lorex.Api.Features.Ideas.Idea", b =>
                {
                    b.Navigation("EntityReferences");

                    b.Navigation("PlotArcReferences");

                    b.Navigation("PlotBeatReferences");

                    b.Navigation("SceneReferences");

                    b.Navigation("StoryReferences");
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityFieldDefinition", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityRevision", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("FieldValues");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.EntityType", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.LoreEntity", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("EntityTags");

                    b.Navigation("FieldValues");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Lorex.Api.Features.Lore.Tag", b =>
                {
                    b.Navigation("EntityTags");
                });

            modelBuilder.Entity("Lorex.Api.Features.Stories.Chapter", b =>
                {
                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("Lorex.Api.Features.Stories.PlotArc", b =>
                {
                    b.Navigation("Beats");
                });

            modelBuilder.Entity("Lorex.Api.Features.Stories.PlotBeat", b =>
                {
                    b.Navigation("EntityLinks");

                    b.Navigation("SceneLinks");
                });

            modelBuilder.Entity("Lorex.Api.Features.Stories.Scene", b =>
                {
                    b.Navigation("EntityLinks");
                });

            modelBuilder.Entity("Lorex.Api.Features.Stories.Story", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("PlotArcs");

                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("Lorex.Api.Features.Timeline.TimelineEntry", b =>
                {
                    b.Navigation("EntityLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
